title: Folding flowers
hero_image: images/banner.png
description: Design a paper cut in code, then fold and cut your own
listed: false
pdf: false
landing: true
steps:
  - title: Step 1
    completion:
      - engaged
  - title: Step 2
    completion:
      - internal
  - title: Challenge
    challenge: true
    completion:
      - external
